/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./*.html"],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
  theme: {
    extend: {
      colors: {
        "background": "#1e0c22",
        "on-secondary": "#3c0090",
        "primary-container": "#ff4dcc",
        "surface-bright": "#46324a",
        "on-secondary-fixed": "#23005b",
        "on-error": "#690005",
        "tertiary": "#c6c6c6",
        "outline-variant": "#56404c",
        "on-secondary-container": "#ddcdff",
        "surface-container-lowest": "#18071d",
        "inverse-primary": "#b1008b",
        "inverse-on-surface": "#3d2941",
        "on-surface": "#f7d9f8",
        "tertiary-container": "#979797",
        "on-primary": "#60004a",
        "surface-container": "#2b192f",
        "on-primary-container": "#5f0049",
        "on-primary-fixed-variant": "#88006a",
        "surface-dim": "#1e0c22",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-fixed": "#ffd8ec",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#464747",
        "error-container": "#93000a",
        "secondary-container": "#7000ff",
        "on-primary-fixed": "#3b002d",
        "on-secondary-fixed-variant": "#5700c9",
        "on-error-container": "#ffdad6",
        "surface": "#1e0c22",
        "surface-container-high": "#36233a",
        "secondary-fixed": "#e9ddff",
        "surface-tint": "#ffaedd",
        "surface-container-low": "#27152b",
        "secondary-fixed-dim": "#d1bcff",
        "surface-container-highest": "#422e45",
        "on-surface-variant": "#ddbecd",
        "inverse-surface": "#f7d9f8",
        "surface-variant": "#422e45",
        "on-tertiary": "#2f3131",
        "on-background": "#f7d9f8",
        "tertiary-fixed": "#e3e2e2",
        "on-tertiary-container": "#2e3030",
        "primary-fixed-dim": "#ffaedd",
        "secondary": "#d1bcff",
        "primary": "#ffaedd",
        "outline": "#a48997",
        "on-tertiary-fixed": "#1a1c1c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        gutter: "20px",
        lg: "48px",
        md: "24px",
        margin: "24px",
        xs: "4px",
        xl: "80px",
        base: "8px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Epilogue"],
        "label-sm": ["Space Grotesk"],
        "headline-lg": ["Epilogue"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
};
